#### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [6]:
import numpy as np

In [10]:
 NumPy= np.arange(1,11,1)
print(NumPy)

[ 1  2  3  4  5  6  7  8  9 10]


#### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [23]:

NumPy=np.zeros((3,3))
NumPy


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
A=np.linspace(0,5, endpoint=False)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [41]:
A=np.random.random((4,4))
A

array([[0.0412912 , 0.25098396, 0.99040738, 0.00951163],
       [0.69218746, 0.11400733, 0.65721105, 0.92297882],
       [0.09940994, 0.77974237, 0.64957578, 0.47085137],
       [0.5740124 , 0.37529396, 0.3755189 , 0.75297584]])

In [53]:
A= np.random.seed(0)
A

In [55]:
A=np.random.rand(4,4)
A

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [57]:
A.shape

(4, 4)

In [61]:
A=np.arange(16)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
x = np.arange(16)
x = x.reshape((4,4))
print (x)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [81]:
B=sum(x)
B

array([24, 28, 32, 36])

Calculate the mean, median, and standard deviation of a NumPy array


In [94]:
B=np.arange(1,16,1)
print(B)
M=np.mean(B)
print(M)
med=np.median(B)
print(med)
st=np.std(B)
print(st)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
8.0
8.0
4.320493798938574


Find the maximum and minimum values in a NumPy array

In [97]:
x = np.arange(16)
x = x.reshape((4,4))
max=np.amax(x)
print(max)
min=np.amin(x)
print(min)

15
0


Create a NumPy array of 20 random integers and find the index of the maximum value.

In [117]:
B=np.random.randint(1,20,(3,3))
B
max_value=np.argmax(B)
max_value


array([[ 3,  3,  4],
       [ 4, 19, 15],
       [ 4, 18, 19]])

Exercise 16:
Create a NumPy array and reverse its elements.

In [119]:
B=np.random.randint(1,20,(3,3))
reverse=B[::1]
print(reverse)

[[15 10  2]
 [ 5 11 12]
 [ 9 12  3]]


#### Exercise
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.



In [122]:
B=np.random.randint(1,20,(3,3))
c=B*B
print(c)

[[289   1   1]
 [ 49 225 121]
 [ 81 196   9]]


#### Exercise 18
Create a diagonal matrix from a given 1D array

In [125]:
C=np.arange(1,12,2)
D=np.diag(C)
print(D)

[[ 1  0  0  0  0  0]
 [ 0  3  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  0  7  0  0]
 [ 0  0  0  0  9  0]
 [ 0  0  0  0  0 11]]


#### Exercise 19
Perform matrix multiplication on two 2D NumPy arrays

In [140]:
C=np.random.randint(1,20,(3,3))
Mul=C*C
Mul

array([[ 16,  16,  64],
       [100, 100, 100],
       [ 16, 225, 361]])

#### Exercise 20
Flatten a 2D NumPy array into a 1D array

In [143]:
B=np.random.randint(1,20,(3,3))
c=B.reshape(9)
c

array([13,  4, 10, 11, 14,  8,  8,  2, 13])

### Exercise 21:
Stack two NumPy arrays vertically

In [170]:
B=np.random.randint(1,20,(3,3))
C=np.random.randint(1,10,(3,3))
d=np.vstack((B,C))
print(d)

[[12 19 14]
 [ 2  7 11]
 [17 17  4]
 [ 2  7  7]
 [ 8  9  9]
 [ 8  1  9]]


#### Exercise 22
Stack two NumPy arrays horizontally.

In [173]:
F=np.hstack((B,C))
print(F)

[[12 19 14  2  7  7]
 [ 2  7 11  8  9  9]
 [17 17  4  8  1  9]]


### Exercise 23
Split a NumPy array into multiple sub-arrays.


In [192]:
B=np.random.randint(1,20,(3,3))
print(B)
new_array=np.split(B,3)
print(new_array)

[[ 3  2 12]
 [ 4 13  5]
 [ 2 18  1]]
[array([[ 3,  2, 12]]), array([[ 4, 13,  5]]), array([[ 2, 18,  1]])]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [210]:
B=np.random.random((3,3))
X=np.round(B,2)
X

array([[0.49, 0.47, 0.88],
       [0.49, 0.41, 0.17],
       [0.48, 0.78, 0.56]])

###  Exercise 25:
Find the unique elements of a NumPy array.

In [216]:
unique_elements=np.unique(X)
print(unique_elements)

[0.17 0.41 0.47 0.48 0.49 0.56 0.78 0.88]


#### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [225]:
X=np.random.randint(1,20,(3,3))
x[x > 4] = 5
print(X)

[[18 19 14]
 [14  3  4]
 [10 13 16]]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [228]:
X=np.random.randint(1,20,(3,3))
sum=np.cumsum(X)
sum

array([ 3, 10, 25, 42, 58, 67, 68, 79, 91])

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [235]:
Non_zero=np.count_nonzero(x)
print(Non_zero)

0


#### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [238]:
n=np.random.randint(1,20,(3,3))
srt=np.sort(n)
srt

array([[ 7,  8, 14],
       [10, 14, 16],
       [ 7, 12, 19]])

#### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [243]:
n=np.random.randint(1,20,(3,3))
c=np.sum(n, axis=0)   
r=np.sum(n, axis=1)
c
r

array([36, 24, 29])